version: "3.9"

services:
# Primser Servicio: WEB
  web:
    build: .
    ports:
      - 8080:5000
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development


# Segundo Servicio
  redis:
    image: "redis:alpine"
